export const vacancyData = [
    {
        id: 1,
        img: "/assets/job1.png",
        name: "Senior UX/UI Dizayner",
        company: "Red Oak Technologies",
        city: "Bakı",
        deadline: "31.12.2024",
    },
    {
        id: 2,
        img: "/assets/job2.png",
        name: "Problemli kreditlər üzrə kiçik mütəxəssis",
        company: "Camal LTD",
        city: "Bakı",
        deadline: "31.12.2024",
    },
    {
        id: 3,
        img: "/assets/job3.png",
        name: "Deputy Project Manager (National)",
        company: "Grandmart",
        city: "Bakı",
        deadline: "31.12.2024",
    }, {
        id: 4,
        img: "/assets/job5.png",
        name: "Risk Management Director",
        company: "System air",
        city: "Bakı",
        deadline: "31.12.2024",
    }, {
        id: 5,
        img: "/assets/job1.png",
        name: "Nümayəndəliklərin idarəedilməsi departamentinin Statistik və analitik təhlil şöbəsinin mütəxəssisi",
        company: "Excelsior Hotel",
        city: "Bakı",
        deadline: "31.12.2024",
    },
    {
        id: 6,
        img: "/assets/job4.png",
        name: "Local recruitment competition: Senior Project Officer",
        company: "One Touch Trade",
        city: "Bakı",
        deadline: "31.12.2024",
    },
    {
        id: 7,
        img: "/assets/job5.png",
        name: "Deputy Project Manager (National)",
        company: "Grandmart",
        city: "Bakı",
        deadline: "31.12.2024",
    },
    {
        id: 8,
        img: "/assets/job2.png",
        name: "Deputy Project Manager (National)",
        company: "Grandmart",
        city: "Bakı",
        deadline: "31.12.2024",
    },
]